[package]
name = "yew-css-and-js-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
wasm-bindgen = "0.2.81"
log = "0.4.6"
wasm-logger = "0.2.0"
gloo = "0.8"
web-sys = "0.3.57"